In [5]:
import pandas as pd

df = pd.read_csv('coffee_shop_sales.csv')
df.head()

,transaction_id,timestamp,store_id,city,country,store_type,product_category,product_name,unit_price,quantity,discount_applied,payment_method,customer_id,customer_age_group,customer_gender,loyalty_member,weather_condition,temperature_c,holiday_name,total_amount
0,10001,2023-01-01 00:39:39,35,Melbourne,AUS,Mall Kiosk,Coffee,Double Espresso,3.04,1,True,Credit Card,qiyfrwsk,35-44,Female,False,Sunny,22.2,New Year's Day,2.74
1,10002,2023-01-01 01:06:53,25,Manchester,UK,Standalone,Coffee,Single Espresso,2.38,2,False,Debit Card,vf0jqqnv,18-24,Male,False,Sunny,8.7,New Year's Day,4.76
2,10003,2023-01-01 02:56:18,23,Manchester,UK,Standalone,Tea,Large Matcha Latte,4.26,2,False,Mobile Wallet,fcd6mzsg,25-34,Male,False,Sunny,8.7,New Year's Day,8.52
3,10004,2023-01-01 02:58:30,38,Toronto,CAN,Standalone,Coffee,Medium Cappuccino,3.68,2,False,Credit Card,jvu2cgxu,55-64,Female,True,Cloudy,-6.5,New Year's Day,7.36
4,10005,2023-01-01 03:13:53,9,Los Angeles,USA,Mall Kiosk,Coffee,Small Cappuccino,3.42,1,False,Mobile Wallet,po4ljedg,18-24,Male,True,Sunny,12.3,New Year's Day,3.42

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   transaction_id      20000 non-null  int64
 1   timestamp           20000 non-null  object
 2   store_id            20000 non-null  int64
 3   city                20000 non-null  object
 4   country             20000 non-null  object
 5   store_type          20000 non-null  object
 6   product_category    20000 non-null  object
 7   product_name        20000 non-null  object
 8   unit_price          20000 non-null  float64
 9   quantity            20000 non-null  int64
 10  discount_applied    20000 non-null  bool
 11  payment_method      20000 non-null  object
 12  customer_id         20000 non-null  object
 13  customer_age_group  18924 non-null  object
 14  customer_gender     18928 non-null  object
 15  loyalty_member      20000 non-null  bool
 16  weather_condition   19022 non-null  object
 17  temperature_c       19022 non-null  float64
 18  holiday_name        335 non-null    object
 19  total_amount        20000 non-null  float64
dtypes: bool(2), float64(3), int64(3), object(12)
memory usage: 2.8+ MB

In [8]:
df.describe(include="all")

,transaction_id,timestamp,store_id,city,country,store_type,product_category,product_name,unit_price,quantity,discount_applied,payment_method,customer_id,customer_age_group,customer_gender,loyalty_member,weather_condition,temperature_c,holiday_name,total_amount
count,20000.000000,20000,20000.000000,20000,20000,20000,20000,20000,20000.000000,20000.00000,20000,20000,20000,18924,18928,20000,19022,19022.000000,335,20000.000000
unique,NaN,19992,NaN,9,4,3,6,43,NaN,NaN,2,4,19250,6,4,2,4,NaN,7,NaN
top,NaN,2023-08-12 09:23:50,NaN,New York,USA,Standalone,Coffee,Croissant,NaN,NaN,False,Credit Card,zjsszwd0,25-34,Female,False,Rainy,NaN,Christmas Day,NaN
freq,NaN,2,NaN,2288,6685,12347,9216,664,NaN,NaN,17631,8344,5,4617,9123,14139,8052,NaN,103,NaN
mean,20000.500000,NaN,23.072950,NaN,NaN,NaN,NaN,NaN,4.049521,1.71265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.556550,NaN,6.850464
std,5773.647028,NaN,13.097332,NaN,NaN,NaN,NaN,NaN,1.982984,1.10808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.184881,NaN,5.989221
min,10001.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,1.640000,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.000000,NaN,1.310000
25%,15000.750000,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,2.820000,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.600000,NaN,3.360000
50%,20000.500000,NaN,23.000000,NaN,NaN,NaN,NaN,NaN,3.690000,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.600000,NaN,4.920000
75%,25000.250000,NaN,34.000000,NaN,NaN,NaN,NaN,NaN,4.750000,2.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.800000,NaN,8.200000
max,30000.000000,NaN,45.000000,NaN,NaN,NaN,NaN,NaN,18.750000,9.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.600000,NaN,112.000000

In [9]:
df.isnull().sum()

transaction_id            0
timestamp                 0
store_id                  0
city                      0
country                   0
store_type                0
product_category          0
product_name              0
unit_price                0
quantity                  0
discount_applied          0
payment_method            0
customer_id               0
customer_age_group     1076
customer_gender        1072
loyalty_member            0
weather_condition       978
temperature_c           978
holiday_name          19665
total_amount              0
dtype: int64

In [10]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['transaction_id', 'timestamp', 'store_id', 'city', 'country',
       'store_type', 'product_category', 'product_name', 'unit_price',
       'quantity', 'discount_applied', 'payment_method', 'customer_id',
       'customer_age_group', 'customer_gender', 'loyalty_member',
       'weather_condition', 'temperature_c', 'holiday_name', 'total_amount'],
      dtype='object')

In [20]:
df['customer_id'].nunique()

19250

In [21]:
df.groupby('product_name')['customer_id'].nunique().sort_values(ascending=False)

product_name
Croissant                     659
Double Espresso               649
Medium Cappuccino             649
Small Mocha                   635
Blueberry Muffin              635
Small Latte                   634
Scone                         634
Medium Americano              633
Medium Latte                  632
Large Cappuccino              629
Medium Mocha                  621
Single Espresso               621
Ham & Cheese Croissant        619
Small Americano               614
Large Latte                   602
Chicken & Avocado Wrap        601
Large Americano               593
Small Cappuccino              585
Chocolate Chip Cookie         577
Large Mocha                   575
Vegan Falafel Wrap            548
Medium Green Tea              448
Medium Chai Latte             433
Large Green Tea               428
Large Matcha Latte            428
Large Chai Latte              427
Small Matcha Latte            424
Medium Berry Blast            423
Small Earl Grey               415
Large Earl Grey               413
Large Berry Blast             402
Small Chai Latte              401
Medium Matcha Latte           400
Medium Earl Grey              374
Small Green Tea               368
Tote Bag                      276
Coffee Mug                    259
Large Iced Coffee             140
Medium Iced Coffee            139
Large Pumpkin Spice Latte     129
Medium Pumpkin Spice Latte    123
Large Tropical Mango           74
Medium Tropical Mango          70
Name: customer_id, dtype: int64

In [22]:
df.groupby('product_category')['customer_id'].nunique()

product_category
Coffee         8994
Merchandise     534
Pastry         2475
Sandwich       1748
Smoothie        964
Tea            4865
Name: customer_id, dtype: int64

In [23]:
df.groupby('product_name')['quantity'].sum().sort_values(ascending=False)

product_name
Medium Cappuccino             1163
Small Mocha                   1146
Croissant                     1137
Double Espresso               1120
Scone                         1103
Blueberry Muffin              1093
Single Espresso               1087
Large Cappuccino              1079
Small Latte                   1068
Medium Americano              1067
Small Americano               1054
Ham & Cheese Croissant        1043
Large Latte                   1041
Medium Latte                  1041
Large Americano               1039
Small Cappuccino              1032
Vegan Falafel Wrap            1028
Medium Mocha                  1013
Chicken & Avocado Wrap         995
Chocolate Chip Cookie          981
Large Mocha                    957
Medium Chai Latte              772
Large Matcha Latte             734
Large Green Tea                732
Large Chai Latte               731
Medium Berry Blast             728
Small Matcha Latte             721
Medium Green Tea               721
Small Earl Grey                720
Small Chai Latte               698
Large Berry Blast              695
Medium Earl Grey               687
Medium Matcha Latte            667
Large Earl Grey                660
Small Green Tea                599
Tote Bag                       484
Coffee Mug                     456
Large Iced Coffee              248
Medium Iced Coffee             236
Large Pumpkin Spice Latte      227
Medium Pumpkin Spice Latte     197
Large Tropical Mango           129
Medium Tropical Mango          124
Name: quantity, dtype: int64

In [24]:
df.groupby('product_name').agg({
    'quantity': 'sum',
    'customer_id': 'nunique',
    'total_amount': 'sum'
}).sort_values(by='total_amount', ascending=False)

                            quantity  customer_id  total_amount
product_name
Tote Bag                         484          276       7021.45
Chicken & Avocado Wrap           995          601       6153.62
Vegan Falafel Wrap              1028          548       5959.89
Ham & Cheese Croissant          1043          619       5476.39
Coffee Mug                       456          259       5197.39
Large Mocha                      957          575       4778.44
Large Cappuccino                1079          629       4761.95
Large Latte                     1041          602       4597.09
Medium Cappuccino               1163          649       4475.58
Small Mocha                     1146          635       4438.59
Medium Mocha                    1013          621       4405.62
Large Berry Blast                695          402       4192.54
Medium Latte                    1041          632       4022.11
Medium Berry Blast               728          423       3869.78
Small Latte                     1068          634       3670.04
Large Matcha Latte               734          428       3648.73
Small Cappuccino                1032          585       3532.04
Large Americano                 1039          593       3431.27
Large Chai Latte                 731          427       3409.43
Blueberry Muffin                1093          635       3150.27
Medium Chai Latte                772          433       3129.77
Double Espresso                 1120          649       3125.61
Medium Americano                1067          633       3066.88
Single Espresso                 1087          621       3032.44
Medium Matcha Latte              667          400       2849.17
Small Matcha Latte               721          424       2794.29
Small Americano                 1054          614       2739.83
Croissant                       1137          659       2712.26
Small Chai Latte                 698          401       2541.85
Scone                           1103          634       2316.50
Large Green Tea                  732          428       2257.42
Large Earl Grey                  660          413       2054.61
Medium Green Tea                 721          448       1937.96
Chocolate Chip Cookie            981          577       1870.23
Medium Earl Grey                 687          374       1835.21
Small Earl Grey                  720          415       1732.80
Small Green Tea                  599          368       1430.86
Large Pumpkin Spice Latte        227          129       1251.00
Large Iced Coffee                248          140        958.45
Medium Pumpkin Spice Latte       197          123        955.98
Medium Iced Coffee               236          139        795.07
Large Tropical Mango             129           74        766.57
Medium Tropical Mango            124           70        662.29

In [11]:
df.groupby('product_category')['total_amount'].sum().sort_values(ascending=False)

product_category
Coffee         58037.99
Tea            29622.10
Sandwich       17589.90
Merchandise    12218.84
Pastry         10049.26
Smoothie        9491.18
Name: total_amount, dtype: float64

In [12]:
df.groupby('city')['total_amount'].sum().sort_values(ascending=False)

city
New York       16789.12
Melbourne      16650.31
Sydney         16612.94
Los Angeles    15596.14
Chicago        15309.60
Toronto        15209.40
Vancouver      15068.80
London         13538.02
Manchester     12234.94
Name: total_amount, dtype: float64

In [13]:
df.groupby('payment_method')['total_amount'].sum()

payment_method
Cash             35882.68
Credit Card      56557.85
Debit Card       23992.40
Mobile Wallet    20576.34
Name: total_amount, dtype: float64

In [14]:
df.groupby('weather_condition')['total_amount'].sum()

weather_condition
Cloudy    23900.61
Rainy     53714.02
Snowy      1812.81
Sunny     50646.31
Name: total_amount, dtype: float64

In [15]:
df.groupby('loyalty_member')['total_amount'].sum()

loyalty_member
False    98372.27
True     38637.00
Name: total_amount, dtype: float64

In [16]:
df.groupby('product_name')['total_amount'].sum().sort_values(ascending=False)

product_name
Tote Bag                      7021.45
Chicken & Avocado Wrap        6153.62
Vegan Falafel Wrap            5959.89
Ham & Cheese Croissant        5476.39
Coffee Mug                    5197.39
Large Mocha                   4778.44
Large Cappuccino              4761.95
Large Latte                   4597.09
Medium Cappuccino             4475.58
Small Mocha                   4438.59
Medium Mocha                  4405.62
Large Berry Blast             4192.54
Medium Latte                  4022.11
Medium Berry Blast            3869.78
Small Latte                   3670.04
Large Matcha Latte            3648.73
Small Cappuccino              3532.04
Large Americano               3431.27
Large Chai Latte              3409.43
Blueberry Muffin              3150.27
Medium Chai Latte             3129.77
Double Espresso               3125.61
Medium Americano              3066.88
Single Espresso               3032.44
Medium Matcha Latte           2849.17
Small Matcha Latte            2794.29
Small Americano               2739.83
Croissant                     2712.26
Small Chai Latte              2541.85
Scone                         2316.50
Large Green Tea               2257.42
Large Earl Grey               2054.61
Medium Green Tea              1937.96
Chocolate Chip Cookie         1870.23
Medium Earl Grey              1835.21
Small Earl Grey               1732.80
Small Green Tea               1430.86
Large Pumpkin Spice Latte     1251.00
Large Iced Coffee              958.45
Medium Pumpkin Spice Latte     955.98
Medium Iced Coffee             795.07
Large Tropical Mango           766.57
Medium Tropical Mango          662.29
Name: total_amount, dtype: float64

In [19]:
df.groupby('customer_age_group')['total_amount'].sum().sort_values(ascending=False)

NameError: name 'transaction_id' is not defined

In [25]:
customer_spend = df.groupby('customer_id')['total_amount'].sum().sort_values(ascending=False)
customer_spend.head()

customer_id
g0l3rtz5    117.40
cy2c11bd    109.56
gb205hu0     91.00
zvvmi177     84.60
164bckbr     82.80
Name: total_amount, dtype: float64

In [26]:
customer_spend.head(10)

customer_id
g0l3rtz5    117.40
cy2c11bd    109.56
gb205hu0     91.00
zvvmi177     84.60
164bckbr     82.80
zuumcnjy     81.00
x3kl5x1x     80.00
ga9ta76n     79.89
za4aeijt     75.00
vwhholi5     75.00
Name: total_amount, dtype: float64

In [27]:
df.groupby('loyalty_member')['total_amount'].agg(['sum', 'mean', 'count'])

                     sum      mean  count
loyalty_member
False           98372.27  6.957513  14139
True            38637.00  6.592220   5861

In [29]:
df.groupby('customer_age_group')['total_amount'].agg(['sum', 'count'])

                         sum  count
customer_age_group
18-24               20028.00   2888
25-34               31645.96   4617
35-44               25414.96   3737
45-54               19310.37   2906
55-64               20030.96   2832
65+                 13111.03   1944

In [32]:
df.groupby('customer_gender')['total_amount'].agg(['sum','count'])

                        sum  count
customer_gender
Female             62519.72   9123
Male               62098.06   9019
Non-binary          2553.39    373
Prefer not to say   2762.40    413

In [36]:
df.groupby('product_name')['quantity'].sum().sort_values(ascending=False).head(10)

product_name
Medium Cappuccino    1163
Small Mocha          1146
Croissant            1137
Double Espresso      1120
Scone                1103
Blueberry Muffin     1093
Single Espresso      1087
Large Cappuccino     1079
Small Latte          1068
Medium Americano     1067
Name: quantity, dtype: int64

In [34]:
df.groupby('product_name')['total_amount'].sum().sort_values(ascending=False).head(10)

product_name
Tote Bag                  7021.45
Chicken & Avocado Wrap    6153.62
Vegan Falafel Wrap        5959.89
Ham & Cheese Croissant    5476.39
Coffee Mug                5197.39
Large Mocha               4778.44
Large Cappuccino          4761.95
Large Latte               4597.09
Medium Cappuccino         4475.58
Small Mocha               4438.59
Name: total_amount, dtype: float64

In [38]:
df.groupby(['customer_age_group', 'product_category'])['total_amount'].agg(['sum','count'])

                                          sum  count
customer_age_group product_category
18-24              Coffee             8711.49   1358
                   Merchandise        1735.13     74
                   Pastry             1530.55    378
                   Sandwich           2388.40    256
                   Smoothie           1413.71    137
                   Tea                4248.72    685
25-34              Coffee            13402.61   2131
                   Merchandise        2524.71    121
                   Pastry             2341.36    579
                   Sandwich           4512.28    429
                   Smoothie           1981.36    204
                   Tea                6883.64   1153
35-44              Coffee            10689.31   1708
                   Merchandise        2284.99    103
                   Pastry             1813.74    462
                   Sandwich           3314.90    343
                   Smoothie           1846.81    185
                   Tea                5465.21    936
45-54              Coffee             8336.78   1349
                   Merchandise        1689.38     74
                   Pastry             1399.53    355
                   Sandwich           2315.57    227
                   Smoothie           1511.10    153
                   Tea                4058.01    748
55-64              Coffee             8466.11   1316
                   Merchandise        1902.50     79
                   Pastry             1433.16    358
                   Sandwich           2616.10    265
                   Smoothie           1362.57    152
                   Tea                4250.52    662
65+                Coffee             5382.93    858
                   Merchandise        1176.70     53
                   Pastry              997.37    254
                   Sandwich           1502.79    163
                   Smoothie            920.62    104
                   Tea                3130.62    512

In [39]:
df.groupby('payment_method')['customer_id'].nunique()

payment_method
Cash             5127
Credit Card      8182
Debit Card       3404
Mobile Wallet    2988
Name: customer_id, dtype: int64

In [42]:
df.groupby('weather_condition')['total_amount'].agg(['sum','count','mean'])

                        sum  count      mean
weather_condition
Cloudy             23900.61   3469  6.889769
Rainy              53714.02   8052  6.670892
Snowy               1812.81    251  7.222351
Sunny              50646.31   7250  6.985698

In [43]:
summary = df.groupby('product_category').agg({
    'total_amount': 'sum',
    'quantity': 'sum',
    'customer_id': 'nunique'
}).sort_values(by='total_amount', ascending=False)

summary

                  total_amount  quantity  customer_id
product_category
Coffee                58037.99     15815         8994
Tea                   29622.10      8442         4865
Sandwich              17589.90      3066         1748
Merchandise           12218.84       940          534
Pastry                10049.26      4314         2475
Smoothie               9491.18      1676          964

In [44]:
import sqlite3

# Create connection
conn = sqlite3.connect('sales.db')

# Save dataframe into SQL table
df.to_sql('sales', conn, if_exists='replace', index=False)

print("✅ SQL table created!")

✅ SQL table created!

In [45]:
query = """
SELECT product_category, SUM(total_amount) AS total_sales
FROM sales
GROUP BY product_category
ORDER BY total_sales DESC;
"""

result = pd.read_sql(query, conn)
result

  product_category  total_sales
0           Coffee     58037.99
1              Tea     29622.10
2         Sandwich     17589.90
3      Merchandise     12218.84
4           Pastry     10049.26
5         Smoothie      9491.18

In [51]:
query = """
SELECT product_name, COUNT(DISTINCT customer_id) AS num_customers
FROM sales
GROUP BY product_name
ORDER BY num_customers DESC;
"""

pd.read_sql(query, conn)

                  product_name  num_customers
0                    Croissant            659
1            Medium Cappuccino            649
2              Double Espresso            649
3                  Small Mocha            635
4             Blueberry Muffin            635
5                  Small Latte            634
6                        Scone            634
7             Medium Americano            633
8                 Medium Latte            632
9             Large Cappuccino            629
10             Single Espresso            621
11                Medium Mocha            621
12      Ham & Cheese Croissant            619
13             Small Americano            614
14                 Large Latte            602
15      Chicken & Avocado Wrap            601
16             Large Americano            593
17            Small Cappuccino            585
18       Chocolate Chip Cookie            577
19                 Large Mocha            575
20          Vegan Falafel Wrap            548
21            Medium Green Tea            448
22           Medium Chai Latte            433
23          Large Matcha Latte            428
24             Large Green Tea            428
25            Large Chai Latte            427
26          Small Matcha Latte            424
27          Medium Berry Blast            423
28             Small Earl Grey            415
29             Large Earl Grey            413
30           Large Berry Blast            402
31            Small Chai Latte            401
32         Medium Matcha Latte            400
33            Medium Earl Grey            374
34             Small Green Tea            368
35                    Tote Bag            276
36                  Coffee Mug            259
37           Large Iced Coffee            140
38          Medium Iced Coffee            139
39   Large Pumpkin Spice Latte            129
40  Medium Pumpkin Spice Latte            123
41        Large Tropical Mango             74
42       Medium Tropical Mango             70

In [52]:
query = """
SELECT product_name, SUM(quantity) AS total_quantity
FROM sales
GROUP BY product_name
ORDER BY total_quantity DESC;
"""

pd.read_sql(query, conn)

                  product_name  total_quantity
0            Medium Cappuccino            1163
1                  Small Mocha            1146
2                    Croissant            1137
3              Double Espresso            1120
4                        Scone            1103
5             Blueberry Muffin            1093
6              Single Espresso            1087
7             Large Cappuccino            1079
8                  Small Latte            1068
9             Medium Americano            1067
10             Small Americano            1054
11      Ham & Cheese Croissant            1043
12                Medium Latte            1041
13                 Large Latte            1041
14             Large Americano            1039
15            Small Cappuccino            1032
16          Vegan Falafel Wrap            1028
17                Medium Mocha            1013
18      Chicken & Avocado Wrap             995
19       Chocolate Chip Cookie             981
20                 Large Mocha             957
21           Medium Chai Latte             772
22          Large Matcha Latte             734
23             Large Green Tea             732
24            Large Chai Latte             731
25          Medium Berry Blast             728
26          Small Matcha Latte             721
27            Medium Green Tea             721
28             Small Earl Grey             720
29            Small Chai Latte             698
30           Large Berry Blast             695
31            Medium Earl Grey             687
32         Medium Matcha Latte             667
33             Large Earl Grey             660
34             Small Green Tea             599
35                    Tote Bag             484
36                  Coffee Mug             456
37           Large Iced Coffee             248
38          Medium Iced Coffee             236
39   Large Pumpkin Spice Latte             227
40  Medium Pumpkin Spice Latte             197
41        Large Tropical Mango             129
42       Medium Tropical Mango             124

In [53]:
query = """
SELECT loyalty_member,
       COUNT(*) AS transactions,
       SUM(total_amount) AS total_spent,
       AVG(total_amount) AS avg_spent
FROM sales
GROUP BY loyalty_member;
"""

pd.read_sql(query, conn)

   loyalty_member  transactions  total_spent  avg_spent
0               0         14139     98372.27   6.957513
1               1          5861     38637.00   6.592220

In [54]:
query = """
SELECT city, SUM(total_amount) AS total_sales
FROM sales
GROUP BY city
ORDER BY total_sales DESC;
"""
pd.read_sql(query, conn)

          city  total_sales
0     New York     16789.12
1    Melbourne     16650.31
2       Sydney     16612.94
3  Los Angeles     15596.14
4      Chicago     15309.60
5      Toronto     15209.40
6    Vancouver     15068.80
7       London     13538.02
8   Manchester     12234.94

In [55]:
query = """
SELECT weather_condition, AVG(total_amount) AS avg_sales
FROM sales
GROUP BY weather_condition;
"""

pd.read_sql(query, conn)

  weather_condition  avg_sales
0              None   7.091534
1            Cloudy   6.889769
2             Rainy   6.670892
3             Snowy   7.222351
4             Sunny   6.985698

In [57]:
query = """
SELECT product_category,
       SUM(total_amount) AS revenue,
       SUM(quantity) AS total_units,
       COUNT(DISTINCT customer_id) AS num_customers
FROM sales
GROUP BY product_category
ORDER BY revenue DESC;
"""

pd.read_sql(query, conn)

  product_category   revenue  total_units  num_customers
0           Coffee  58037.99        15815           8994
1              Tea  29622.10         8442           4865
2         Sandwich  17589.90         3066           1748
3      Merchandise  12218.84          940            534
4           Pastry  10049.26         4314           2475
5         Smoothie   9491.18         1676            964